import type { Child } from 'hono/jsx'
import { event, sessions, speakers } from '../data/runtime'

export const AdminLayout = ({ title, children }: { title: string; children: Child }) => <html lang="ja"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><title>{title} / 管理画面</title><style>{adminCss}</style></head><body><main class="admin-shell"><header><a href="/admin">SANDA / ADMIN</a><nav><a href="/">公開サイト</a><form method="post" action="/admin/logout"><button>ログアウト</button></form></nav></header>{children}</main></body></html>

export const Field = ({ label, name, value = '', type = 'text', required = false }: { label: string; name: string; value?: string | number; type?: string; required?: boolean }) => <label><span>{label}</span><input type={type} name={name} value={String(value)} required={required} /></label>
export const Textarea = ({ label, name, value = '', required = false }: { label: string; name: string; value?: string; required?: boolean }) => <label><span>{label}</span><textarea name={name} required={required}>{value}</textarea></label>
export const Csrf = ({ value }: { value: string }) => <input type="hidden" name="csrf" value={value} />

export const Dashboard = ({ csrf }: { csrf: string }) => <AdminLayout title="Dashboard"><h1>管理画面</h1><div class="admin-grid"><a class="admin-card" href="/admin/event"><b>イベント情報</b><span>{event.title}</span></a><a class="admin-card" href="/admin/speakers"><b>登壇者</b><span>{speakers.length}人</span></a><a class="admin-card" href="/admin/sessions"><b>セッション</b><span>{sessions.length}枠</span></a></div><p class="hint">変更内容は保存すると公開ページへ即時反映されます。</p><form method="post" action="/admin/ogp"><Csrf value={csrf} /><button class="primary">イベントOGPを再生成</button></form></AdminLayout>

export const Login = ({ error = '' }: { error?: string }) => <html lang="ja"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><title>管理画面ログイン</title><style>{adminCss}</style></head><body><main class="login"><form method="post" action="/admin/login"><h1>SANDA / ADMIN</h1>{error && <p class="error">{error}</p>}<label><span>管理者パスワード</span><input type="password" name="password" autocomplete="current-password" required /></label><button class="primary">ログイン</button></form></main></body></html>

export const EventForm = ({ csrf }: { csrf: string }) => <AdminLayout title="イベント情報"><h1>イベント情報</h1><form class="form" method="post" action="/admin/event"><Csrf value={csrf} /><Field label="イベント名" name="title" value={event.title} required /><Field label="短縮名" name="shortTitle" value={event.shortTitle} required /><Textarea label="説明" name="description" value={event.description} required /><Field label="日付表示" name="dateLabel" value={event.dateLabel} required /><Field label="一般参加時間" name="timeLabel" value={event.timeLabel} required /><Field label="準備時間" name="setupTimeLabel" value={event.setupTimeLabel} required /><Field label="会場" name="venue" value={event.venue} required /><Field label="会場詳細" name="venueDetail" value={event.venueDetail} required /><Field label="参加費" name="fee" value={event.fee} required /><Field label="定員" name="capacity" value={event.capacity} required /><Field label="connpass URL" name="connpassUrl" value={event.connpassUrl} type="url" required /><Field label="配信 URL" name="streamUrl" value={event.streamUrl ?? ''} type="url" /><button class="primary">保存</button></form></AdminLayout>

export const SpeakerList = ({ csrf }: { csrf: string }) => <AdminLayout title="登壇者"><div class="title-row"><h1>登壇者</h1><a class="button primary" href="/admin/speakers/new">追加</a></div><div class="list">{speakers.map((speaker) => <article><div><b>{speaker.name}</b><span>{speaker.role} / {speaker.category}</span></div><a href={`/admin/speakers/${speaker.id}`}>編集</a></article>)}</div></AdminLayout>

export const SpeakerForm = ({ csrf, speaker }: { csrf: string; speaker?: (typeof speakers)[number] }) => <AdminLayout title={speaker ? '登壇者編集' : '登壇者追加'}><h1>{speaker ? '登壇者編集' : '登壇者追加'}</h1><form class="form" method="post" action={speaker ? `/admin/speakers/${speaker.id}` : '/admin/speakers/new'} enctype="multipart/form-data"><Csrf value={csrf} /><Field label="ID" name="id" value={speaker?.id ?? ''} required /><Field label="名前" name="name" value={speaker?.name ?? ''} required /><Field label="ハンドル" name="handle" value={speaker?.handle ?? ''} /><Field label="肩書き" name="role" value={speaker?.role ?? ''} required /><Field label="分野" name="category" value={speaker?.category ?? 'other'} required /><Textarea label="紹介文" name="bio" value={speaker?.bio ?? ''} required /><label><span>アイコン画像</span><input type="file" name="icon" accept="image/jpeg,image/png,image/webp" /></label><label class="check"><input type="checkbox" name="online" checked={speaker?.online ?? false} />オンライン出演</label><button class="primary">保存</button></form>{speaker && <form method="post" action={`/admin/speakers/${speaker.id}/delete`}><Csrf value={csrf} /><button class="danger">削除</button></form>}</AdminLayout>

export const SessionList = ({ csrf }: { csrf: string }) => <AdminLayout title="セッション"><div class="title-row"><h1>セッション</h1><a class="button primary" href="/admin/sessions/new">追加</a></div><div class="list">{sessions.map((session) => <article><div><b>{session.start}〜{session.end} {session.title}</b><span>{session.category} / {session.speakerIds.map((id) => speakers.find((speaker) => speaker.id === id)?.name).filter(Boolean).join(' / ') || '―'}</span></div><a href={`/admin/sessions/${session.id}`}>編集</a></article>)}</div></AdminLayout>

export const SessionForm = ({ csrf, session }: { csrf: string; session?: (typeof sessions)[number] }) => <AdminLayout title={session ? 'セッション編集' : 'セッション追加'}><h1>{session ? 'セッション編集' : 'セッション追加'}</h1><form class="form" method="post" action={session ? `/admin/sessions/${session.id}` : '/admin/sessions/new'}><Csrf value={csrf} /><Field label="ID" name="id" value={session?.id ?? ''} required /><Field label="日付" name="date" value={session?.date ?? '2026-11-02'} required /><Field label="開始" name="start" value={session?.start ?? '10:00'} required /><Field label="終了" name="end" value={session?.end ?? '10:10'} required /><Field label="タイトル" name="title" value={session?.title ?? ''} required /><Field label="カテゴリ (talk / special / break)" name="category" value={session?.category ?? 'talk'} required /><Field label="色 (white / yellow / blue / green / red)" name="color" value={session?.color ?? 'yellow'} required /><Textarea label="概要" name="summary" value={session?.summary ?? ''} required /><Textarea label="詳細" name="detail" value={session?.detail ?? ''} required /><label><span>登壇者（複数選択）</span><select name="speakerIds" multiple size={Math.min(8, speakers.length)}>{speakers.map((speaker) => <option value={speaker.id} selected={session?.speakerIds.includes(speaker.id)}>{speaker.name}</option>)}</select></label><button class="primary">保存</button></form>{session && <form method="post" action={`/admin/sessions/${session.id}/delete`}><Csrf value={csrf} /><button class="danger">削除</button></form>}</AdminLayout>

const adminCss = `:root{font-family:Arial,Hiragino Kaku Gothic ProN,Yu Gothic,sans-serif;color:#171719;background:#ededf0}*{box-sizing:border-box}body{margin:0}.admin-shell,.login{width:min(960px,calc(100% - 32px));margin:0 auto;padding:32px 0 80px}.admin-shell header{display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid;padding-bottom:18px;margin-bottom:42px}.admin-shell header a{font-weight:900;text-decoration:none}.admin-shell nav{display:flex;gap:16px;align-items:center}.admin-shell nav form{margin:0}h1{font-size:48px;margin:0 0 32px}a,.button{color:inherit}.admin-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.admin-card{display:grid;gap:12px;padding:24px;border:2px solid;background:#fff;text-decoration:none}.admin-card span,.list span,.hint{color:#68686d}.form{display:grid;gap:18px;max-width:680px}.form label{display:grid;gap:7px;font-weight:800;font-size:13px}.form input,.form textarea,.form select{width:100%;border:2px solid;padding:11px;background:#fff;font:inherit}.form textarea{min-height:120px;resize:vertical}.form select{min-height:130px}.check{display:flex!important;grid-template-columns:auto 1fr;display:grid!important;align-items:center}.check input{width:auto}.primary,.button,.danger{display:inline-flex;width:max-content;border:2px solid;padding:11px 16px;background:#5b83ef;color:#171719;font-weight:900;text-decoration:none;cursor:pointer}.danger{background:#ed654e;margin-top:22px}.title-row{display:flex;justify-content:space-between;align-items:center}.list{border-top:2px solid}.list article{display:flex;justify-content:space-between;gap:20px;align-items:center;padding:18px 0;border-bottom:2px solid}.list article div{display:grid;gap:7px}.error{padding:12px;background:#ed654e}.login{min-height:100vh;display:grid;place-items:center}.login form{width:min(420px,100%);display:grid;gap:18px;padding:28px;border:2px solid;background:#fff}.login h1{font-size:32px}.login label{display:grid;gap:7px;font-weight:800}.login input{border:2px solid;padding:11px;font:inherit}@media(max-width:700px){.admin-grid{grid-template-columns:1fr}h1{font-size:38px}.admin-shell header{align-items:flex-start;gap:15px;flex-direction:column}}`
